### ISSUE TITLE
Running or Building the Example Vue app fails due to an error with Colorette

### ISSUE THREAD

**Issue by DominicFinn** [MyUNiDAYS/unidays-connect#12]
Ive cloned the example, ran `npm install` followed by `npm run serve` or `npm run build` and recieve the following error:

```
ERROR  Error: Package exports for '/Users/dominicfinn/git/github/unidays-connect/src/vue/node_modules/colorette' do not define a valid '.' target
```

Reading in this a little more I'd followed this issue in colorette https://github.com/jorgebucaran/colorette/issues/49#issuecomment-678421134 which leads down to https://github.com/postcss/autoprefixer/issues/1353#issuecomment-674598226 

At the moment the solution appears to be just not using node v 13.

**Comment by jimgolfgti** [comment]
Cannot recreate, tried with
node: 14.9.0, npm: 6.14.8 (Current)
node: 13.14.0, npm: 6.14.4 (Previous)
node: 12.14.3, npm: 6.14.6 (LTS)

In all attempts the project built and ran successfully.

Please post exact versions you are using.

Steps followed when attempting to recreate.
```sh
nvm install M.m.p
nvm use M.m.p
npm install -g @vue/cli
npm ci
npm run build
```

**Comment by jimgolfgti** [comment]
Closing as this is not an issue directly with example / cannot recreate
